Software Factory - DevSecOps

diff --git a/devsecops/build/buildspec-anchore.yml b/devsecops/build/buildspec-anchore.yml
--- a/devsecops/build/buildspec-anchore.yml
+++ b/devsecops/build/buildspec-anchore.yml
@@ -35,12 +35,12 @@ phases:
       - echo ""
       - |
         if (grep -E 'High|Critical' payload.json); then
-          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
           echo "There are critical or high vulnerabilities.. failing the build"
           docker push $REPOSITORY_URI:latest
           exit 1;
         elif (grep -E 'Medium' payload.json); then
-          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
           docker push $REPOSITORY_URI:latest
         else
           docker push $REPOSITORY_URI:latest
diff --git a/devsecops/build/buildspec-ecr.yml b/devsecops/build/buildspec-ecr.yml
--- a/devsecops/build/buildspec-ecr.yml
+++ b/devsecops/build/buildspec-ecr.yml
@@ -44,11 +44,11 @@ phases:
       - echo ""
       - |
         if (grep -E 'HIGH|CRITICAL' ecr_scan_result.json); then
-          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
           echo "There are critical or high vulnerabilities.. failing the build"
           exit 1;
         elif (grep -E 'MEDIUM' ecr_scan_result.json); then
-          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
         fi
       - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
       - kubectl patch deployment wordpress-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"build\":\"dev-123456\"}}}}}}"
