Software Factory - DevSecOps

diff --git a/devsecops/build/buildspec-anchore.yml b/devsecops/build/buildspec-anchore.yml
--- a/devsecops/build/buildspec-anchore.yml
+++ b/devsecops/build/buildspec-anchore.yml
@@ -18,34 +18,43 @@ phases:
     commands:
       - echo "inside build stage"
       - cd $CODEBUILD_SRC_DIR
-      - docker build . -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION -f dockerfile-wp.dockerfile
-      - curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- -r $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
-      - TAG="$CODEBUILD_RESOLVED_SOURCE_VERSION"
-      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPOSITORY_URI:latest
+      - SOURCE_COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
+      - IMG_TAG=${SOURCE_COMMIT_HASH:-latest}
+      - docker build . -t $IMAGE_REPO_NAME:$IMG_TAG -f dockerfile-wp.dockerfile
+      ## To scan the container image
+      - curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- -r $IMAGE_REPO_NAME:$IMG_TAG
+      - docker tag $IMAGE_REPO_NAME:$IMG_TAG $REPOSITORY_URI:latest
+      - docker tag $IMAGE_REPO_NAME:$IMG_TAG $REPOSITORY_URI:$IMG_TAG
       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
   post_build:
     commands:
       - |
         jq "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"ANCHORE\", \
-        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
+        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \
+        \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
         \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
         \"build_id\": env.CODEBUILD_BUILD_ID, \
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" anchore-reports/*-vuln.json > payload.json
       - echo ""
-      - |
-        if (grep -E 'High|Critical' payload.json); then
-          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-          echo "There are critical or high vulnerabilities.. failing the build"
-          docker push $REPOSITORY_URI:latest
-          exit 1;
-        elif (grep -E 'Medium' payload.json); then
-          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-          docker push $REPOSITORY_URI:latest
-        else
-          docker push $REPOSITORY_URI:latest
-        fi
-      - printf '[{"name":"hello-k8s","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
+      # - |
+      #   if (grep -E 'High|Critical' payload.json); then
+      #     aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+      #     echo "There are critical or high vulnerabilities.. failing the build"
+      #     docker push $REPOSITORY_URI:latest
+      #     docker push $REPOSITORY_URI:$IMG_TAG
+      #     exit 1;
+      #   elif (grep -E 'Medium' payload.json); then
+      #     aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json anchore-reports/*-vuln.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+      #     docker push $REPOSITORY_URI:latest
+      #     docker push $REPOSITORY_URI:$IMG_TAG
+      #   else
+      #     docker push $REPOSITORY_URI:latest
+      #     docker push $REPOSITORY_URI:$IMG_TAG
+      #   fi
+      - docker push $REPOSITORY_URI:latest
+      - docker push $REPOSITORY_URI:$IMG_TAG
+      - printf '[{"name":"anchore-k8s","imageUri":"%s"}]' $REPOSITORY_URI:$IMG_TAG > build.json
 artifacts:
   type: zip
   files: '**/*'
diff --git a/devsecops/build/buildspec-ecr.yml b/devsecops/build/buildspec-ecr.yml
--- a/devsecops/build/buildspec-ecr.yml
+++ b/devsecops/build/buildspec-ecr.yml
@@ -28,31 +28,32 @@ phases:
             echo "ECR scan failed";
             exit 1;
           fi
-          stat=$(aws ecr describe-image-scan-findings --repository-name eks-container-repo --image-id imageTag=latest | jq -r '.imageScanStatus.status');
+          stat=$(aws ecr describe-image-scan-findings --repository-name $IMAGE_REPO_NAME --image-id imageTag=latest | jq -r '.imageScanStatus.status');
           sleep 5;
         done
-      - aws ecr describe-image-scan-findings --repository-name eks-container-repo --image-id imageTag=latest > ecr_scan_result.json
+      - aws ecr describe-image-scan-findings --repository-name $IMAGE_REPO_NAME --image-id imageTag=latest > ecr_scan_result.json
   post_build:
     commands:
       - |
         jq "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"ECR\", \
-        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
+        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \
+        \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
         \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
         \"build_id\": env.CODEBUILD_BUILD_ID, \
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" ecr_scan_result.json > payload.json
       - echo ""
-      - |
-        if (grep -E 'HIGH|CRITICAL' ecr_scan_result.json); then
-          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-          echo "There are critical or high vulnerabilities.. failing the build"
-          exit 1;
-        elif (grep -E 'MEDIUM' ecr_scan_result.json); then
-          aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-        fi
+      # - |
+      #   if (grep -E 'HIGH|CRITICAL' ecr_scan_result.json); then
+      #     aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+      #     echo "There are critical or high vulnerabilities.. failing the build"
+      #     exit 1;
+      #   elif (grep -E 'MEDIUM' ecr_scan_result.json); then
+      #     aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json ecr_scan_result.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+      #   fi
       - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
-      - kubectl patch deployment wordpress-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"build\":\"dev-123456\"}}}}}}"
-      - printf '[{"name":"hello-k8s","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
+      - kubectl patch deployment wordpress-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"build\":\"$CODEBUILD_RESOLVED_SOURCE_VERSION\"}}}}}}"
+      - printf '[{"name":"ecr-k8s","imageUri":"%s"}]' $REPOSITORY_URI:$IMG_TAG > build.json
 artifacts:
   type: zip
   files: '**/*'
diff --git a/devsecops/build/buildspec-snyk.yml b/devsecops/build/buildspec-snyk.yml
--- a/devsecops/build/buildspec-snyk.yml
+++ b/devsecops/build/buildspec-snyk.yml
@@ -16,35 +16,40 @@ phases:
     commands:
       - echo "inside build stage"
       - cd $CODEBUILD_SRC_DIR
-      - docker build . -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION -f dockerfile-wp.dockerfile
+      - SOURCE_COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
+      - IMG_TAG=${SOURCE_COMMIT_HASH:-latest}
+      - docker build . -t $IMAGE_REPO_NAME:$IMG_TAG -f dockerfile-wp.dockerfile
       # Snyk Auth using API token
       - snyk config set api=$SnykApiKey
       ## To scan the container image
-      - snyk container test $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION --file=dockerfile-wp.dockerfile --json --severity-threshold=high > snyk-results.json
-      - TAG="$CODEBUILD_RESOLVED_SOURCE_VERSION"
-      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $REPOSITORY_URI:latest
+      - snyk container test $IMAGE_REPO_NAME:$IMG_TAG --file=dockerfile-wp.dockerfile --json --severity-threshold=high > snyk-results.json
+      - docker tag $IMAGE_REPO_NAME:$IMG_TAG $REPOSITORY_URI:latest
+      - docker tag $IMAGE_REPO_NAME:$IMG_TAG $REPOSITORY_URI:$IMG_TAG
       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
   post_build:
     commands:
       - |
         jq "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"SNYK\", \
-        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
+        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \
+        \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
         \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
         \"build_id\": env.CODEBUILD_BUILD_ID, \
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" snyk-results.json > payload.json
       - echo ""
-      - |
-        if (grep -E 'high|critical' payload.json); then
-          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-          echo "There are critical or high vulnerabilities.. failing the build"
-          docker push $REPOSITORY_URI:latest
-          exit 1;
-        elif (grep -E 'medium|low' payload.json); then
-          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-          docker push $REPOSITORY_URI:latest
-        fi
-      - printf '[{"name":"hello-k8s","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
+      # - |
+      #   if (grep -E 'high|critical' payload.json); then
+      #     aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+      #     echo "There are critical or high vulnerabilities.. failing the build"
+      #     docker push $REPOSITORY_URI:latest
+      #     docker push $REPOSITORY_URI:$IMG_TAG
+      #     exit 1;
+      #   elif (grep -E 'medium|low' payload.json); then
+      #     aws lambda invoke --function-name import-securityhub-eks-function --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+      #     docker push $REPOSITORY_URI:latest
+      #     docker push $REPOSITORY_URI:$IMG_TAG
+      #   fi
+      - printf '[{"name":"snyk-k8s","imageUri":"%s"}]' $REPOSITORY_URI:$IMG_TAG > build.json
 artifacts:
   type: zip
   files: '**/*'
